PASSWORD_HASH VARCHAR(255) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AULA (
ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
NIVEL VARCHAR(40) NOT NULL,
GRADO INT NOT NULL,
SECCION CHAR(1) NOT NULL,
VACANTES_TOTALES INT NOT NULL,
VACANTES_DISPONIBLES INT NOT NULL
);

CREATE TABLE RESERVA (
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
ID_ALUMNO INT NOT NULL,
ID_AULA INT NOT NULL,
CODIGO_PAGO VARCHAR(20) UNIQUE NOT NULL,
FECHA_RESERVA DATETIME DEFAULT CURRENT_TIMESTAMP,
ESTADO_PAGO VARCHAR(50) DEFAULT 'PENDIENTE'
);

CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(200) NOT NULL,
    ESTADO TINYINT(1) DEFAULT 1
);

-- RELACION ENTRE TABLAS ---

ALTER TABLE RESERVA 
ADD CONSTRAINT FK_RELACION1
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO (ID_ALUMNO);

ALTER TABLE RESERVA 
ADD CONSTRAINT FK_RELACION2
FOREIGN KEY (ID_AULA) REFERENCES AULA (ID_AULA);

-- INFORMACION--

INSERT INTO AULA (nivel, grado, seccion, vacantes_totales, vacantes_disponibles) VALUES
('Secundaria', 3, 'A', 30, 5),
('Secundaria', 3, 'B', 30, 0),
('Primaria', 1, 'A', 25, 25),
('Primaria', 6, 'B', 30, 12);

INSERT INTO USUARIO (USERNAME,PASSWORD_HASH)
VALUES ('Admin','$2y$10$heuMG7aElXF5IiS4rCN49.T.smRQfhlCmVuoAh/SPpjQ6YA6qzZO6');
