CREATE DATABASE MATRICULA
USE MATRICULA

CREATE TABLE ALUMNO (
ID_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
DNI_ALUMNO CHAR(8) UNIQUE NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(80) NOT NULL,
FECHA_NAC DATE NOT NULL,
EDAD INT NOT NULL,
GENERO VARCHAR(1) NOT NULL,
DIRECCION VARCHAR(100) NOT NULL,
CELULAR CHAR(9) NOT NULL,
CORREO VARCHAR(80) UNIQUE NOT NULL,
APODERADO_NOMBRE VARCHAR(100) NOT NULL,
APODERADO_CELULAR CHAR(9) NOT NULL,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR(255) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AULA (
ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
NIVEL VARCHAR(40) NOT NULL,
GRADO INT NOT NULL,
SECCION CHAR(1) NOT NULL,
VACANTES_TOTALES INT NOT NULL,
VACANTES_DISPONIBLES INT NOT NULL
);

CREATE TABLE RESERVA (
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
ID_ALUMNO INT NOT NULL,
ID_AULA INT NOT NULL,
CODIGO_PAGO VARCHAR(20) UNIQUE NOT NULL,
FECHA_RESERVA DATETIME DEFAULT CURRENT_TIMESTAMP,
ESTADO_PAGO VARCHAR(50) DEFAULT 'PENDIENTE'
);

-- RELACION ENTRE TABLAS ---

ALTER TABLE RESERVA 
ADD CONSTRAINT FK_RELACION1
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO (ID_ALUMNO);

ALTER TABLE RESERVA 
ADD CONSTRAINT FK_RELACION2
FOREIGN KEY (ID_AULA) REFERENCES AULA (ID_AULA);